In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    "Name": [
        "Rahul", "Priya", "Arjun", "Sneha", "Kiran",
        "Anjali", "Ravi", "Divya", "Suresh", "Meena"
    ],

    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Age": [
        20, 21, 20, 22, 21,
        20, 22, 21, 20, 22
    ],

    "Study_Hours": [
        4, 6, 3, 7, 5,
        8, 2, 6, 4, 7
    ],

    "Attendance": [
        85, 92, 78, 95, 88,
        96, 70, 90, 82, 94
    ],

    "Math": [
        75, 88, 65, 92, 80,
        95, 55, 86, 72, 90
    ],

    "Science": [
        78, 90, 70, 94, 82,
        96, 60, 88, 75, 92
    ],

    "English": [
        80, 85, 68, 90, 79,
        93, 65, 84, 70, 88
    ]
}

df = pd.DataFrame(data)

df

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Math,Science,English
0,101,Rahul,Male,20,4,85,75,78,80
1,102,Priya,Female,21,6,92,88,90,85
2,103,Arjun,Male,20,3,78,65,70,68
3,104,Sneha,Female,22,7,95,92,94,90
4,105,Kiran,Male,21,5,88,80,82,79
5,106,Anjali,Female,20,8,96,95,96,93
6,107,Ravi,Male,22,2,70,55,60,65
7,108,Divya,Female,21,6,90,86,88,84
8,109,Suresh,Male,20,4,82,72,75,70
9,110,Meena,Female,22,7,94,90,92,88

In [12]:
df.to_csv("student_performance.csv", index=False)

In [14]:
df = pd.read_csv("student_performance.csv")

df

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Math,Science,English
0,101,Rahul,Male,20,4,85,75,78,80
1,102,Priya,Female,21,6,92,88,90,85
2,103,Arjun,Male,20,3,78,65,70,68
3,104,Sneha,Female,22,7,95,92,94,90
4,105,Kiran,Male,21,5,88,80,82,79
5,106,Anjali,Female,20,8,96,95,96,93
6,107,Ravi,Male,22,2,70,55,60,65
7,108,Divya,Female,21,6,90,86,88,84
8,109,Suresh,Male,20,4,82,72,75,70
9,110,Meena,Female,22,7,94,90,92,88

In [15]:
df.head()

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Math,Science,English
0,101,Rahul,Male,20,4,85,75,78,80
1,102,Priya,Female,21,6,92,88,90,85
2,103,Arjun,Male,20,3,78,65,70,68
3,104,Sneha,Female,22,7,95,92,94,90
4,105,Kiran,Male,21,5,88,80,82,79

In [16]:
df.tail()

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Math,Science,English
5,106,Anjali,Female,20,8,96,95,96,93
6,107,Ravi,Male,22,2,70,55,60,65
7,108,Divya,Female,21,6,90,86,88,84
8,109,Suresh,Male,20,4,82,72,75,70
9,110,Meena,Female,22,7,94,90,92,88

In [17]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 10
Columns: 9

In [18]:
print(df.columns)

Index(['Student_ID', 'Name', 'Gender', 'Age', 'Study_Hours', 'Attendance',
       'Math', 'Science', 'English'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   10 non-null     int64
 1   Name         10 non-null     object
 2   Gender       10 non-null     object
 3   Age          10 non-null     int64
 4   Study_Hours  10 non-null     int64
 5   Attendance   10 non-null     int64
 6   Math         10 non-null     int64
 7   Science      10 non-null     int64
 8   English      10 non-null     int64
dtypes: int64(7), object(2)
memory usage: 852.0+ bytes

In [20]:
df.describe()

,Student_ID,Age,Study_Hours,Attendance,Math,Science,English
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,105.50000,20.900000,5.200000,87.000000,79.800000,82.500000,80.200000
std,3.02765,0.875595,1.932184,8.353309,12.942608,11.692828,9.681598
min,101.00000,20.000000,2.000000,70.000000,55.000000,60.000000,65.000000
25%,103.25000,20.000000,4.000000,82.750000,72.750000,75.750000,72.250000
50%,105.50000,21.000000,5.500000,89.000000,83.000000,85.000000,82.000000
75%,107.75000,21.750000,6.750000,93.500000,89.500000,91.500000,87.250000
max,110.00000,22.000000,8.000000,96.000000,95.000000,96.000000,93.000000

In [21]:
df.describe()

,Student_ID,Age,Study_Hours,Attendance,Math,Science,English
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,105.50000,20.900000,5.200000,87.000000,79.800000,82.500000,80.200000
std,3.02765,0.875595,1.932184,8.353309,12.942608,11.692828,9.681598
min,101.00000,20.000000,2.000000,70.000000,55.000000,60.000000,65.000000
25%,103.25000,20.000000,4.000000,82.750000,72.750000,75.750000,72.250000
50%,105.50000,21.000000,5.500000,89.000000,83.000000,85.000000,82.000000
75%,107.75000,21.750000,6.750000,93.500000,89.500000,91.500000,87.250000
max,110.00000,22.000000,8.000000,96.000000,95.000000,96.000000,93.000000

In [22]:
df.isnull().sum()

Student_ID     0
Name           0
Gender         0
Age            0
Study_Hours    0
Attendance     0
Math           0
Science        0
English        0
dtype: int64

In [23]:
df.loc[2, "Math"] = np.nan
df.loc[5, "Science"] = np.nan

df.isnull().sum()

Student_ID     0
Name           0
Gender         0
Age            0
Study_Hours    0
Attendance     0
Math           1
Science        1
English        0
dtype: int64

In [24]:
df["Math"] = df["Math"].fillna(df["Math"].mean())

df["Science"] = df["Science"].fillna(
    df["Science"].mean()
)

In [25]:
df.isnull().sum()

Student_ID     0
Name           0
Gender         0
Age            0
Study_Hours    0
Attendance     0
Math           0
Science        0
English        0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df["Total_Marks"] = (
    df["Math"] +
    df["Science"] +
    df["English"]
)

df.head()

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Math,Science,English,Total_Marks
0,101,Rahul,Male,20,4,85,75.000000,78.0,80,233.000000
1,102,Priya,Female,21,6,92,88.000000,90.0,85,263.000000
2,103,Arjun,Male,20,3,78,81.444444,70.0,68,219.444444
3,104,Sneha,Female,22,7,95,92.000000,94.0,90,276.000000
4,105,Kiran,Male,21,5,88,80.000000,82.0,79,241.000000

In [28]:
df["Total_Marks"]

0    233.000000
1    263.000000
2    219.444444
3    276.000000
4    241.000000
5    269.000000
6    180.000000
7    258.000000
8    217.000000
9    270.000000
Name: Total_Marks, dtype: float64

In [29]:
df["Math"] + df["Science"] + df["English"]

0    233.000000
1    263.000000
2    219.444444
3    276.000000
4    241.000000
5    269.000000
6    180.000000
7    258.000000
8    217.000000
9    270.000000
dtype: float64

In [30]:
df["Average_Marks"] = (
    df["Total_Marks"] / 3
)

df["Average_Marks"] = df["Average_Marks"].round(2)

df.head()

,Student_ID,Name,Gender,Age,Study_Hours,Attendance,Math,Science,English,Total_Marks,Average_Marks
0,101,Rahul,Male,20,4,85,75.000000,78.0,80,233.000000,77.67
1,102,Priya,Female,21,6,92,88.000000,90.0,85,263.000000,87.67
2,103,Arjun,Male,20,3,78,81.444444,70.0,68,219.444444,73.15
3,104,Sneha,Female,22,7,95,92.000000,94.0,90,276.000000,92.00
4,105,Kiran,Male,21,5,88,80.000000,82.0,79,241.000000,80.33

In [31]:
def performance_category(mark):
    if mark >= 90:
        return "Excellent"
    elif mark >= 75:
        return "Good"
    elif mark >= 60:
        return "Average"
    else:
        return "Poor"


df["Performance"] = df["Average_Marks"].apply(
    performance_category
)

df[["Name", "Average_Marks", "Performance"]].head(10)

     Name  Average_Marks Performance
0   Rahul          77.67        Good
1   Priya          87.67        Good
2   Arjun          73.15     Average
3   Sneha          92.00   Excellent
4   Kiran          80.33        Good
5  Anjali          89.67        Good
6    Ravi          60.00     Average
7   Divya          86.00        Good
8  Suresh          72.33     Average
9   Meena          90.00   Excellent

In [32]:
top_students = df.sort_values(
    by="Average_Marks",
    ascending=False
)

top_students[
    ["Name", "Average_Marks", "Performance"]
].head(5)

     Name  Average_Marks Performance
3   Sneha          92.00   Excellent
9   Meena          90.00   Excellent
5  Anjali          89.67        Good
1   Priya          87.67        Good
7   Divya          86.00        Good

In [33]:
lowest_students = df.sort_values(
    by="Average_Marks",
    ascending=True
)

lowest_students[
    ["Name", "Average_Marks", "Performance"]
].head(5)

     Name  Average_Marks Performance
6    Ravi          60.00     Average
8  Suresh          72.33     Average
2   Arjun          73.15     Average
0   Rahul          77.67        Good
4   Kiran          80.33        Good

In [34]:
high_attendance = df[df["Attendance"] >= 90]

print("Students with 90% or more attendance:")
print(high_attendance[[
    "Name",
    "Attendance",
    "Average_Marks"
]])

Students with 90% or more attendance:
     Name  Attendance  Average_Marks
1   Priya          92          87.67
3   Sneha          95          92.00
5  Anjali          96          89.67
7   Divya          90          86.00
9   Meena          94          90.00

In [35]:
low_attendance = df[df["Attendance"] < 75]

print("Students with less than 75% attendance:")

if len(low_attendance) > 0:
    print(low_attendance[[
        "Name",
        "Attendance",
        "Average_Marks"
    ]])
else:
    print("No students found with attendance below 75%.")

Students with less than 75% attendance:
   Name  Attendance  Average_Marks
6  Ravi          70           60.0

In [36]:
high_study = df[df["Study_Hours"] > 5]

print("Students studying more than 5 hours:")

print(high_study[[
    "Name",
    "Study_Hours",
    "Average_Marks"
]])

Students studying more than 5 hours:
     Name  Study_Hours  Average_Marks
1   Priya            6          87.67
3   Sneha            7          92.00
5  Anjali            8          89.67
7   Divya            6          86.00
9   Meena            7          90.00

In [37]:
low_study = df[df["Study_Hours"] <= 5]

print("Students studying 5 hours or less:")

print(low_study[[
    "Name",
    "Study_Hours",
    "Average_Marks"
]])

Students studying 5 hours or less:
     Name  Study_Hours  Average_Marks
0   Rahul            4          77.67
2   Arjun            3          73.15
4   Kiran            5          80.33
6    Ravi            2          60.00
8  Suresh            4          72.33

In [38]:
gender_average = df.groupby(
    "Gender"
)["Average_Marks"].mean()

print("Gender-wise Average Marks:")

print(gender_average.round(2))

Gender-wise Average Marks:
Gender
Female    89.07
Male      72.70
Name: Average_Marks, dtype: float64

In [39]:
gender_attendance = df.groupby(
    "Gender"
)["Attendance"].mean()

print("Gender-wise Average Attendance:")

print(gender_attendance.round(2))

Gender-wise Average Attendance:
Gender
Female    93.4
Male      80.6
Name: Attendance, dtype: float64

In [40]:
subject_average = df[
    ["Math", "Science", "English"]
].mean()

print("Subject-wise Average Marks:")
print(subject_average.round(2))

Subject-wise Average Marks:
Math       81.44
Science    81.00
English    80.20
dtype: float64

In [41]:
study_analysis = df.groupby(
    "Study_Hours"
)["Average_Marks"].mean()

print("Study Hours vs Average Marks:")
print(study_analysis.round(2))

Study Hours vs Average Marks:
Study_Hours
2    60.00
3    73.15
4    75.00
5    80.33
6    86.84
7    91.00
8    89.67
Name: Average_Marks, dtype: float64

In [42]:
attendance_analysis = df.groupby(
    "Attendance"
)["Average_Marks"].mean()

print("Attendance vs Average Marks:")
print(attendance_analysis.round(2))

Attendance vs Average Marks:
Attendance
70    60.00
78    73.15
82    72.33
85    77.67
88    80.33
90    86.00
92    87.67
94    90.00
95    92.00
96    89.67
Name: Average_Marks, dtype: float64

In [43]:
correlation = df[
    [
        "Study_Hours",
        "Attendance",
        "Math",
        "Science",
        "English",
        "Average_Marks"
    ]
].corr()

print("Correlation Matrix:")
print(correlation.round(2))

Correlation Matrix:
               Study_Hours  Attendance  Math  Science  English  Average_Marks
Study_Hours           1.00        0.97  0.90     0.85     0.97           0.95
Attendance            0.97        1.00  0.92     0.92     0.96           0.98
Math                  0.90        0.92  1.00     0.84     0.87           0.95
Science               0.85        0.92  0.84     1.00     0.86           0.94
English               0.97        0.96  0.87     0.86     1.00           0.95
Average_Marks         0.95        0.98  0.95     0.94     0.95           1.00